development:
  adapter: postgresql
  encoding: utf8
  database: mtg_deck_manager_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mtg_deck_manager_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mtg_deck_manager_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
